### PR TITLE
send bot messages to IRC

### PR DESCRIPTION
**Pull request by hexwab**

### CODE REVIEW

**Comment by iMartyn** [comment]
Seems sensible to me.

**Comment by ultrafez** [comment]
I haven't tried it out myself, but presumably since IRC messages appear in Slack as bot messages, it doesn't cause an infinite loop of IRC messages on Slack being mirrored back to IRC does it?

**Comment by hexwab** [comment]
Entirely possible, would need testing. As it is, I don't know how to try this locally as it's some crazy node thing.

**Comment by ultrafez** [comment]
It shouldn't be too hard to test - the README file looks like it includes fairly good setup instructions. You'll need to get a Slack API token to include in your config file, which is something Martyn should be able to help with.

**Pull request closed without merging**
